<h1>
	Welcome to UpStage</h1>
<p>
	UpStage is an open source web-based platform for cyberformance - live online performance by remote performers, for online audiences. Everything happens in a web browser, in real time. UpStage is an unfunded, artist-led project and we welcome your involvement - as artists, audience, and developers. Visit the <a href="http://upstage.org.nz/blog">UpStage web site</a> for more information.</p>
<p>
<h1>
	UpStage Workshop</h1>
    <p> Note: Please login to access the Workshop in order to create and edit Stages and Media</p>
	Shows available from this Foyer:</p>
<p>
	<a href="javascript:navStages()">Current Stages</a></p>
<p>
	Note: you will need Adobe Flash Player to watch the performances. This is a standard plug-in for most web browsers, but if you don&#39;t have it, it&#39;s free to download from the <a href="http://www.adobe.com/go/getflashplayer" target="other">Adobe site.</a></p>
<h1>
	UpStage Stage List</h1>
<p>
	Your name is %(username)s</p>
<p>
	The following stages are viewable on this UpStage server:</p>
<p>
	%(list)s</p>
<h1>
	Next Show:</h1>
<p>
	[Title &amp; description] <a class="bodyl" href="#">go to stage... </a> <script type="text/javascript">countPlayerAndAudience();</script></p>
